### ISSUE TITLE
change npm's `go-ipfs` module to point to this repo

### ISSUE THREAD

**Issue by harlantwood** [ipfs/go-ipfs-dep#4]
right now the readme for this repo says:

> Installation
> `npm install go-ipfs --save`

But if you do that, it installs the module at https://github.com/ipfs/npm-go-ipfs, not this one.

If I understand correctly, either we should push the code of this repo to npm's `go-ipfs` module, or change the readme of this repo.

**Comment by diasdavid** [comment]
now https://github.com/ipfs/npm-go-ipfs uses go-ipfs-dep. go-ipfs-dep is just to download the binary. Hope it makes more sense now (hard to name these things)

**Comment by harlantwood** [comment]
thanks 😉
